name: genai
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - git=2.51.2=h57928b3_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.5.4=h725018a_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.11.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - brotli==1.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - diffusers==0.36.0.dev0
      - dill==0.4.0
      - exceptiongroup==1.3.0
      - fastapi==0.121.0
      - ffmpy==0.6.4
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lpips==0.1.4
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - modelscope==1.31.0
      - mogrify==0.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.3
      - numpy==2.1.2
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==11.3.0
      - platformdirs==4.5.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.3
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentry-sdk==2.43.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.49.3
      - sympy==1.14.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.0+cu128
      - torch-fidelity==0.3.0
      - torchvision==0.24.0+cu128
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.22.3
      - websockets==15.0.1
      - wget==3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: D:\Anaconda3\envs\genai
